### ISSUE TITLE
Quicken is unable to complete your request.[OL-221-A]

### ISSUE THREAD

**Issue by toadicusrex** [ScottUlmer/CSV-QFX#1]
It lists [OL-221-B] as the only description for the bug, there's nothing else.  On Quicken's site it says there's a formatting problem.  I've been trying to figure it out but I'm thinking I might need to download the source to do so.  Any idea what you would need to figure out what might be causing the problem?

**Comment by ScottUlmer** [comment]
Hey yes it would be a formatting issue, typically it has to deal with the date from my experience. Can you upload a sterilized version of your CSV? I can take a look and run it through the program and get back to you. The dollar amount does not matter and also the place does not matter, but if there is any "odd" characters in it, please leave it in, just in case (but feel free to change all "normal" text.

**Comment by toadicusrex** [comment]
I uploaded it as "Sanitized Transactions".  Thank you for looking into it!

**Comment by ScottUlmer** [comment]
Howdy sir, okay so "you" have two issues. The first in in your amounts you have a comma, with a CSV file it should not have commas in numbers (since they are how to tell it where to split). If you format that column as a number with two decimals and without commas that fixes the first issue. The second is more an issue with my program for some reason your date being m/d/yyyy format is causing an issue. I will look into it when I get sometime (hopefully in the next few weeks). However, there is a pretty easy manual fix for this on your end. If you select your data column and format it as a number without decimal and without commas it works (this format is called serial date in Excel). The first date on your file would be 42979 for example. I will take a look at making a more permanent solution for you in the future. Sorry for the bugs. Let me know if you have any other issues.
In case any of this was unclear you can look at the CSV I uploaded (same spot as yours). It is called "Sanitized Transactions (Fixed).csv".

**Comment by toadicusrex** [comment]
That's wonderful - I'm a developer myself, and I appreciate the quick
turnaround.  I don't mind modifying the data, this is probably just a
one-time fix for me (though I've had to do it twice now, I guess...)  I'll
give that a shot and report.  Thanks, Scott!

**Comment by ScottUlmer** [comment]
Hey Toadicsrex you are very welcome. I think I got BOTH issues resolved. If you could uninstall the program and then reinstall using this installer to let me know if it is fix, I would appreciate it. Once I get your approval I will close this ticket and upload the new installer as an official release. Thanks for your support!

https://1drv.ms/f/s!AsoEVAi18zs6lFKBNgNAjtKlHlyh

**Comment by toadicusrex** [comment]
Worked like a charm.  Thank you so much!  Sorry for the delay, corporate
issues at my office have me pulled in too many directions.  Thanks for your
help!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
